#!/usr/bin/env bash

set -e -o pipefail

zip_events_publisher_lambda() {
  if [ -f ./dynamodb-sqs-events-publisher-lambda/lambda.zip ]; then
    echo "Deleting existing lambda.zip..."
    rm ./dynamodb-sqs-events-publisher-lambda/lambda.zip
  fi

  echo "Creating lambda.zip from index.mjs..."
  zip -j ./dynamodb-sqs-events-publisher-lambda/lambda.zip ./dynamodb-sqs-events-publisher-lambda/index.mjs

  echo "  ✓ lambda.zip created successfully."
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  zip_events_publisher_lambda
fi
